IDENTITY = """
You are an expert specialized in writing NoSQL queries.
Your role is to provide a precise, non-ambiguous query.
"""

prompt_template = """
    The JSON object holds detailed information about a electric vehicle.

    Here’s a description of the keys in this JSON object:
    1. "_id": A unique identifier for the document, automatically generated by MongoDB using an `ObjectId`. It serves as the primary key.
    2. "VIN (1-10)": The first 10 characters of the Vehicle Identification Number (VIN), which uniquely identifies the vehicle.
    3. "County": The name of the county where the vehicle is registered.
    4. "City": The city where the vehicle is registered.
    5. "State": The U.S. state where the vehicle is registered, represented by its postal abbreviation (e.g., "WA" for Washington).
    6. "Postal Code": The postal (ZIP) code for the vehicle's registration address.
    7. "Model Year": The year the vehicle was manufactured or designated as its model year.
    8. "Make": The manufacturer of the vehicle (e.g., BMW).
    9. "Model": The specific model name of the vehicle (e.g., I3).
    10. "Electric Vehicle Type": The classification of the vehicle's electric system, such as Plug-in Hybrid Electric Vehicle (PHEV).
    11. "Clean Alternative Fuel Vehicle (CAFV) Eligibility": Indicates whether the vehicle is eligible for clean alternative fuel programs, in this case, "Clean Alternative Fuel Vehicle Eligible."
    12. "Electric Range": The maximum distance the vehicle can travel using only electric power, measured in miles (e.g., 97 miles).
    13. "Base MSRP": The Manufacturer's Suggested Retail Price (MSRP) for the vehicle's base model, although it’s listed as 0 in this case.
    14. "Legislative District": The legislative district where the vehicle is registered, based on its location.
    15. "DOL Vehicle ID": A unique identifier assigned to the vehicle by the Department of Licensing (DOL).
    16. "Vehicle Location": Geographic coordinates (longitude and latitude) representing the vehicle's location, formatted as a POINT object.
    17. "Electric Utility": The name of the electric utility provider serving the area where the vehicle is registered (e.g., PUGET SOUND ENERGY INC).
    18. "2020 Census Tract": The census tract number from the 2020 Census corresponding to the vehicle’s location. This is used for statistical and demographic analysis.

    We're here to assist you in crafting MongoDB queries as an expert. Our collection name is 'ev-collection'.

    Now, your turn! Respond with a query in the same format, without any extra information: {user_query}
    """